In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
df = pd.read_csv('Churn_Modelling.csv')
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [4]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
ann = tf.keras.models.Sequential()

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [11]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [12]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 352us/step - accuracy: 0.7405 - loss: 0.5447
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 329us/step - accuracy: 0.7979 - loss: 0.4617
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - accuracy: 0.8025 - loss: 0.4410
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 324us/step - accuracy: 0.8095 - loss: 0.4266
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 324us/step - accuracy: 0.8177 - loss: 0.4134
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 324us/step - accuracy: 0.8261 - loss: 0.3995
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - accuracy: 0.8340 - loss: 0.3862
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 334us/step - accuracy: 0.8435 - loss: 0.3749
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - accuracy: 0.8490 - loss: 0.3680
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.8514 - loss: 0.3626
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - accuracy: 0.8556 - loss: 0.3584
Epoch 12/100
250/25

In [19]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


array([[False]])

In [20]:
y_pred = ann.predict(X_test)
y_pred = ( y_pred > 0.5 )

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 300us/step


In [21]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1513   82]
 [ 198  207]]


0.86